name: website-uptime

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install matplotlib==3.7.1

      - name: Run script
        run: |
          python3 generate_graph.py 
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          branch=${branch#refs/heads/}
          git checkout $branch
          git pull origin $branch
          git add *.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update all news.*.md" && git push origin $branch)
